"""added uuid column

Revision ID: 364bcb84a9a2
Revises: 44a6051066d0
Create Date: 2014-01-02 00:38:27.371099

"""

# revision identifiers, used by Alembic.
revision = '364bcb84a9a2'
down_revision = '44a6051066d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('uuid_id', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'uuid_id')
    ### end Alembic commands ###
