"""added reply_to column

Revision ID: 44a6051066d0
Revises: 58e91fcb69e1
Create Date: 2014-01-01 21:34:22.052778

"""

# revision identifiers, used by Alembic.
revision = '44a6051066d0'
down_revision = '58e91fcb69e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('reply_to', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'reply_to')
    ### end Alembic commands ###
