"""<insert message here>

Revision ID: 58e91fcb69e1
Revises: None
Create Date: 2013-12-31 21:31:19.895733

"""

# revision identifiers, used by Alembic.
revision = '58e91fcb69e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('anonymous', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'anonymous')
    ### end Alembic commands ###
